### ISSUE TITLE
[Autoconfigure] First impressions

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [leangen/graphql-spqr-spring-boot-starter#1]
Hi there!

Congratulations on this amazing GraphQL spring boot extension, it was really easy to setup our current spring boot project to use this `graphql-spqr-spring-boot-autoconfigure` dependency.

To help this project get even better, I would like to suggest a few improvements:

- Remove the SPQR banner. This is a dependency, so it should not add a banner to the project.
- Document the `spring-boot-starter-websocket` dependency. Without this the application crashes after booting up.

Best regards,
Rafael Renan Pacheco.

**Comment by BaldyLocks** [comment]
Hi, I'll remove the banner today, as for documenting this I'll probably start working on it during the weekend. And the websocket config will likely have a major rehaul when SPQR 0.9.8 is published.

**Comment by BaldyLocks** [comment]
Any useful ideas and suggestions are more than welcome. Thanks for trying it out at such an early stage !

**Comment by BaldyLocks** [comment]
Banner moved to test classpath in latest snapshot.

**Comment by rafaelrenanpacheco** [comment]
Hi there!

Did you deploy to maven the newest snapshot? I'm still getting the banner after updating the dependencies.

Best regards,
Rafael Pacheco.

**Comment by BaldyLocks** [comment]
We're not deploying snapshots now. It will be deployed as part of 0.0.2 , you can build 0.0.2-SNAPSHOT locally though or just replace it with your own banner.

**Comment by waeljammal** [comment]
Hi, would be good if dynamic proxies were supported as well, instead of having to register every type with the schemaGenerator if thats possible.

**Comment by kaqqao** [comment]
@waeljammal The problem with dynamic proxy classes (at least until Java modules become the norm and access to `Unsafe` is completely removed) is that they do not have to be generated in the same package as the original class, which breaks a few features. Also, depending on the way the proxy is generated, typing information can get lost. This is why SPQR needs explicit types provided in there cases.
