### ISSUE TITLE
Unable to upgrade to `Spring Boot` version `2.7.x`

### ISSUE THREAD

**Issue by x80486** [leangen/graphql-spqr-spring-boot-starter#119]
Would it be possible to get a new release some time this year? Currently I'm unable to upgrade to `Spring Boot` version `2.7.x` :grimacing:

**Comment by MarcinLachowicz** [comment]
I would love to have it too

**Comment by kicktipp** [comment]
It is such a wonderful project, but it is not up-to-date (again). I need to fix it locally to use spring 2.7.

**Comment by kicktipp** [comment]
You can fix it in your gradle build like this:

```
plugins {
    id 'org.springframework.boot' version "2.7.3"
    // to use  ext['graphql-java.version'] this plugin is needed:
    id "io.spring.dependency-management" version "1.0.13.RELEASE"
}

// https://github.com/leangen/graphql-spqr-spring-boot-starter/issues/119
ext['graphql-java.version'] = '16.2'
```

**Comment by SaschaPeukert** [comment]
@kicktipp Any maven version for this?

**Comment by SaschaPeukert** [comment]
With Spring-Boot 3.0.0 this problem seems to have become even bigger aka its not compatible anymore because spring changed that [spring.factories](https://github.com/leangen/graphql-spqr-spring-boot-starter/blob/master/graphql-spqr-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories) mechanism

**Comment by kaqqao** [comment]
If any of you would like to help upgrade this to the latest Spring Boot and SPQR versions, please do.

**Comment by michael-simons** [comment]
I see the following issues

- The GraphQL library that is referenced by Boot 2.7 is newer than the one supported with the current product. To align both, you'll have to bump the `spqr.version` first
- There are some deprecation warnings, that are easily fixed as far as I can tell

A necessary change is to adapt how the auto configuration is loaded. Spring Boot 2.7 supports the old way (with `spring.factories`) and the new way (with `org.springframework.boot.autoconfigure.AutoConfiguration.imports` plus using now `@AutoConfiguration`, with the latter not allowing to proxy `@Bean` methods anymore, but you are doing that anyway).

I'll send a PR in a sec addressing these things. Feel free to edit whatever you want, especially my changes unrelated to auto config (I don't have a clue honestly how the SPQR / GraphQL system works, I'm just here with my dear colleague @SaschaPeukert). The remaining changes to auto config are sane and will allow proper usage in at least Boot 2.7 and most likely with Boot 3 (given that the GraphQL version is compatible).

**Comment by michael-simons** [comment]
You made the configurational class bean on its own and you can't auto inject into the overloaded method. I pushed this down, so that the configurer is a bean on its own rights, inject the executor. That should work.
