### ISSUE TITLE
release 0.0.7 to maven central

### ISSUE THREAD

**Issue by indentia** [leangen/graphql-spqr-spring-boot-starter#123]

**Comment by indentia** [comment]
When will 0.0.7 be released?

**Comment by ErtugrulSener** [comment]
Bump.
When will the 0.0.7 be released? What is missing?

**Comment by kaqqao** [comment]
Released. Next release will likely be based on the Spring GraphQL starter, which implicitly will bump Spring Boot to v3.

**Comment by kaqqao** [comment]
It will also contain major breaking changes unfortunately. As all the framework/infrastructure code will no come from Spring GraphQL and not SPQR....

**Comment by ErtugrulSener** [comment]
@kaqqao Thank you very much for the quick response & release!
