### ISSUE TITLE
Support Apollo's graphql-ws protocol

### ISSUE THREAD

**Issue by kaqqao** [leangen/graphql-spqr-spring-boot-starter#13]
[Apollo's graphql-ws protocol](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md) for GraphQl over WebSocket is currently the only way to get subscriptions working out of the box.

This starter should thus implement it.

**Comment by baksosapi** [comment]
when v.0.9.9 will release?

**Comment by kaqqao** [comment]
It's out :)
