### ISSUE TITLE
Spring Boot 3 Support?

### ISSUE THREAD

**Issue by ErtugrulSener** [leangen/graphql-spqr-spring-boot-starter#133]
Anyone knows if we can use graphql-spqr with Spring Boot 3?
Is there any plans on doing that?

Could I maybe help, by just "testing" if this works and pointing out what needs to be changed? Maybe even do some changes?

**Comment by kaqqao** [comment]
Technically, only one single line needs to change to make it compatible with Spring Boot 3 (javax -> jakarta package change).
I have somewhat lofty goals for the next version of the starter, and am knee-deep in that. But instead of finishing all that before I release a Spring Boot 3 compatible version, I should just make the minimal changes and publish an intermediary release to enable people to using it while I'm working on the new stuff... I'll do this by next weekend.

**Comment by ErtugrulSener** [comment]
> Technically, only one single line needs to change (apart from bumping the dependency versions) to make it compatible with Spring Boot 3 (javax -> jakarta package change).
> 
> I have somewhat lofty goals for the next version of the starter, and am knee-deep in that. But instead of finishing all that before I release a Spring Boot 3 compatible version, I should just make the minimal changes and publish an intermediary release to enable people to using it while I'm working on the new stuff... I'll do this by next weekend.

That sounds awesome! ❤️

**Comment by ErtugrulSener** [comment]
> Technically, only one single line needs to change (apart from bumping the dependency versions) to make it compatible with Spring Boot 3 (javax -> jakarta package change).
> 
> I have somewhat lofty goals for the next version of the starter, and am knee-deep in that. But instead of finishing all that before I release a Spring Boot 3 compatible version, I should just make the minimal changes and publish an intermediary release to enable people to use it while I'm working on the new stuff... I'll do this by next weekend.

Hey @kaqqao - You still working on that? You need a helping hand?

**Comment by russm3086** [comment]
> > Technically, only one single line needs to change (apart from bumping the dependency versions) to make it compatible with Spring Boot 3 (javax -> jakarta package change).
> > I have somewhat lofty goals for the next version of the starter, and am knee-deep in that. But instead of finishing all that before I release a Spring Boot 3 compatible version, I should just make the minimal changes and publish an intermediary release to enable people to use it while I'm working on the new stuff... I'll do this by next weekend.
> 
> Hey @kaqqao - You still working on that? You need a helping hand?

Any update?

**Comment by manshanb** [comment]
@kaqqao Any update on this ? As springboot 2.7 is nearing End of Life, upgrade to Springboot 3 is critical for us.

**Comment by mdtamim** [comment]
@kaqqao I see code changes related to Spring Boot 3 has been merged to the main branch.Can you please release a major version also so that we can start pulling that dependency from Maven repo?

**Comment by ErtugrulSener** [comment]
The PR by @SaschaPeukert has been accepted, now we need a new version.
Should we choose "1.0.0" as this is a major update?

@kaqqao

**Comment by kaqqao** [comment]
> Should we choose "1.0.0" as this is a major update?

I... don't know 😓 The version after this will be based on the Spring GraphQL starter, so another major change... So I either name this 1.0.0 and the next 2.0.0 already, or we still keep 0.x even though this is a big change... I don't like either proposition too much 🫤
What do you say?

**Comment by kaqqao** [comment]
Ok.
This release will be 1.0.0 (making 1.x the _classic_ SPQR Starter branch) and the Spring GraphQL starter based ones will be 2.x.  Seems nice and intuitive enough.

**Comment by kaqqao** [comment]
Released
