### ISSUE TITLE
failed to request http://localhost:8080/graphql   caused by  graphql.AssertException: query can't be null

### ISSUE THREAD

**Issue by lucStev1n** [leangen/graphql-spqr-spring-boot-starter#134]
springboot version: 2.7.10

dependencies: 
![R9`3~JP9{GEJAP$4ILV FRT](https://github.com/leangen/graphql-spqr-spring-boot-starter/assets/93248132/1d6aad73-e87f-4440-9572-7945cac52625)

service:
![)7{AW9F{KHHZX8VYB$_`CG7](https://github.com/leangen/graphql-spqr-spring-boot-starter/assets/93248132/97b25e42-8300-4b27-b9f9-45e8382d1f56)

**Comment by lucStev1n** [comment]
> 

openjdk 11

**Comment by kaqqao** [comment]
The error says you didn't send a query.  Did you?
