### ISSUE TITLE
starter 1.0.1 - Duplicate type mappers of type .JsonArrayAdapter

### ISSUE THREAD

**Issue by casey1111** [leangen/graphql-spqr-spring-boot-starter#142]
After pulling the new v1.0.01 starter to resolve the parameters compilation issue with Spring Boot 3.2, project is now failing with the following:

`Failed to instantiate [io.leangen.graphql.ExecutableSchema]: Factory method 'graphQLExecutableSchema' threw exception with message: Duplicate type mappers of type io.leangen.graphql.module.common.jackson.JsonArrayAdapter registered
`

With Spring Boot 3.1, and graphql-spqr 1.0.0, it compiles fine. Any ideas what could be happening? I am adding few custom scalars to GraphQLSchemaGenerator, but nothing related to array. Thanks for any help, hints..

**Comment by esc-sbarden** [comment]
I you have your own GraphQLSchema defined. 
```java
@Bean
GraphQLSchema graphQLSchema(GraphQLSchemaGenerator schemaGenerator) {
    //do something
    return schemaGenerator.generate();
}
```


You may need to change this to something like this:

``` java
@Bean
public ExecutableSchema graphQLExecutableSchema(GraphQLSchemaGenerator schemaGenerator) {
    return schemaGenerator.generateExecutable();
}

@Bean
public GraphQLSchema graphQLSchema(ExecutableSchema executableSchema) {
    return executableSchema.getSchema();
}
```

**Comment by casey1111** [comment]
Fantastic! Works perfectly.  Thank you! Never would have figured that out myself.

**Comment by kaqqao** [comment]
Aaah, yes. Really should have documented this in the changelog as potentially breaking. What @esc-sbarden said is correct. If you were modifying how `GraphQLSchema` is created, please switch to modifying `ExecutableSchema` creation instead.

I'll also try to make this more tolerant in the next release... I'm sure it's possible to detect the situation and handle it gracefully. Sorry for the regression :/
