### ISSUE TITLE
Websockets with GraphQL Playground

### ISSUE THREAD

**Issue by cmdavinder** [leangen/graphql-spqr-spring-boot-starter#15]
I  am using 0.0.2 version. If I enable websocket support via `graphql.spqr.ws.enabled=true `then websockets doesn't work with GraphQL Playground. It appears that `SockJsHttpRequestHandler `is being used by the app instead of `PerConnectionWebSocketHandler`. See below line from application startup logs - 

`Mapped URL path [/graphql/**] onto handler of type [class org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler]`

Can anyone help with this? I have been using SPQR to build an app from last 3 months but because of Websocket support issues my development work is not crippled. :(  I don't want to write a separate NodeJs app with Apollo server.

**Comment by kaqqao** [comment]
In 0.0.2 Apollo's graphql-ws protocol (expected by Playground) is not supported, but it has been added to 0.0.3 #13.
