### ISSUE TITLE
Support Spring Data paging out of the box

### ISSUE THREAD

**Issue by kaqqao** [leangen/graphql-spqr-spring-boot-starter#2]
Firstly, we must make sure Spring Data paging types (`Page`, `Pageable`) map nicely out of the box.

Additionally, we should have custom mappers, and whatever else necessary, to optionally automatically map Spring paging style to Relay Connection style.

A similar issue was raised in SPQR (https://github.com/leangen/graphql-spqr/issues/127).

**Comment by kezhenxu94** [comment]
> Firstly, we must make sure Spring Data paging types (`Page`, `Pageable`) map nicely out of the box.
> 
> Additionally, we should have custom mappers, and whatever else necessary, to optionally automatically map Spring paging style to Relay Connection style.
> 
> A similar issue was raised in SPQR ([leangen/graphql-spqr#127](https://github.com/leangen/graphql-spqr/issues/127)).

@kaqqao Any update on this issue? I've tried to implement it myself but I can only get the `Pageable`Input work, the returning `Page` is still unsupported, can you elaborate more on how to get `Page` work? thanks

**Comment by kezhenxu94** [comment]
Hi @kaqqao , I've finally got this work, and seems this project is not that actively developed, are contributions(PR) welcomed? If that's the case I'll send a pull request :) thanks

**Comment by yaadyaad** [comment]
Hi @kezhenxu94 , looking forward for your PR as well )

**Comment by kaqqao** [comment]
Hey everyone. Sorry for the radio silence. There were big internal changes in SPQR that took much of the effort, but with that out of the way, this project and this issue in specific is back in focus.

There's already a PR dealing with one part of the problem, and I've locally worked out most the remaining bits. I aim to release a new version of the starter with this issue resolved in a week or less.

**Comment by kaqqao** [comment]
One thing I have not worked out yet is whether generating type-specific sorts, so that you have an enum with fields that can be sorted on instead of a simple string is worth it or not.

E.g.

Imagine an object type `Book` with `title`, `isbn` and `releaseDate` fields. And that a list of books can be sorted on `title` or `releaseDate`, but not `isbn` (for whatever reason). A dedicated enum type could be generated that contained the 2 fields used for sorting, so that the client would know the possible values.

I have an experimental implementation of this, but there's a few different ways it can fit with Spring Data paging mechanism and I'm not sure how important it is...

If you have an opinion on this, please voice it here (or on Gitter).

**Comment by blagerweij** [comment]
For me, a String would be good enough (for now, MVP), turning this into an enum later would be nice. What's the status on this issue, can we get it merged?

**Comment by temecom** [comment]
Is this branch ready to be merged? We are looking for an out of the box solution and borrowed form this but it would be nice to have it in the master branch. Thanks Chris
