### ISSUE TITLE
HttpServletRequest's problem

### ISSUE THREAD

**Issue by ghostxbh** [leangen/graphql-spqr-spring-boot-starter#26]
Hello, I'd like to know how the HttpServletRequest request in the SPQR controller is passed to the service.

**Comment by kaqqao** [comment]
Please open Spring Starter related issues in the appropriate project. I moved this one already.

The request object is available via `DefaultGlobalContext#getNativeRequest` (the method name changed in v0.0.4).

`DefaultGlobalContext` is the object oassed as the GraphQL context by default (you can change this) and, as such, can be injected into service methods using `@GraphQLRootContext`.

**Comment by zl5465** [comment]
Thank you，I'm looking forward to the new version.
