### ISSUE TITLE
GraphQLSubscription "InvalidDefinitionException" error

### ISSUE THREAD

**Issue by safaksahin** [leangen/graphql-spqr-spring-boot-starter#30]
Hi,

I'm newbie to spring reactive so this question can be silly, sorry for that.
I'm trying to use graphqlsubscription from looking to the example.
Here is my code:

`private final ConcurrentMultiMap<String, FluxSink<ExpDTO>> subscribers = new ConcurrentMultiMap<>();

 @GraphQLSubscription
    public Publisher<ExpDTO> expUpdated(String code) {
    	 return Flux.create(subscriber -> subscribers.add(code, subscriber.onDispose(() -> subscribers.remove(code, subscriber))), FluxSink.OverflowStrategy.LATEST);
    }`

And here is the error:

> org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class graphql.execution.reactive.CompletionStageMappingPublisher]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class graphql.execution.reactive.CompletionStageMappingPublisher and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.LinkedHashMap["data"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:293) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]

**Comment by kaqqao** [comment]
The current starter doesn't yet support subscriptions in conjunction with WebFlux. If I'm not mistaken, that's what you meant by _Spring reactive_, right?
Subscriptions currently only work with Spring MVC (i.e. non-reactive apps).

**Comment by safaksahin** [comment]
Yes, i meant spring reactive. Thanks :)

**Comment by Andrulez** [comment]
@kaqqao Could you please add more detail to your explanation?  [This exapmle](https://github.com/leangen/graphql-spqr-samples/tree/master/spring-boot-starter-sample) uses projectreactor for subscription demo but you write "The current starter doesn't yet support subscriptions in conjunction with WebFlux".

**Comment by kaqqao** [comment]
@Andrulez Subscriptions require a `Publisher` (and this is all SPQR cares about) and Reactor provides a convenient `Publisher` implementation, so you can use it freely (or RxJava if you prefer). And as long as your application is servlet based (Spring MVC) subscriptions will work out of the box, as the WebSocket backend is there.

What's not implemented is the reactive WebSocket part, and this is why subscriptions won't work out of the box in a WebFlux application. You can implement that part yourself of course using the servlet-based impl as an inspiration, but it's a non trivial effort. Built-in support is coming in the future.

**Comment by Andrulez** [comment]
@kaqqao Thank you for the answer and many other extremely useful answers on Stackoverflow! They helped me many times!

**Comment by manousos** [comment]
please try one of them http://www.reactive-streams.org/reactive-streams-flow-adapters-1.0.2-javadoc/org/reactivestreams/FlowAdapters.html
