### ISSUE TITLE
Upload Or Download Operation Implement

### ISSUE THREAD

**Issue by CengSin** [leangen/graphql-spqr-spring-boot-starter#40]
how can i upload or download excel by Graphql-spqe-spring-boot-starter

**Comment by sahmadov** [comment]
Maybe some dirty code like this will help you:
```
    @GraphQLMutation
    public Collection<TemplateItem>  uploadTemplate(@GraphQLNonNull @GraphQLArgument(name = "itemTemplate") byte[] uploadFile) {
        Xcelite uploadTemplate = new Xcelite(Files.write(Files.createTempFile("temp", ".xlsx"), uploadFile).toFile());
        CustomBeanSheetReader<TemplateItem> reader = new CustomBeanSheetReader<>(uploadTemplate.getSheet(0), TemplateItem.class);
        reader.skipHeaderRow(true);

        return reader.read();
    }
```

Basically you get byte array and use some libs to process them.


Lib that I use is:

```
<dependency>
<groupId>com.ebay</groupId>
<artifactId>xcelite</artifactId>
            <version>${xcelite.version}</version>
        </dependency>
```

**Comment by kaqqao** [comment]
Uploading/downloading binaries is currently inconvenient in SPQR, but not impossible. You'd need to override the provided controller with your own and decide how you want to receive the queries and binaries, and how you want to send the results and binaries back. To override the controller, just provide your own bean of `GraphQLController` type.

Your best bet is implementing the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec], which thanks to Spring shouldn't be too complicated.

Btw you can always get to the raw request by injecting `@GraphQLRootContext DefaultGlobalContext<NativeWebRequest> request` as a method argument. From there you can obtain input and output streams.

You can also wire in a custom `ArgumentInjector` that can inject something more precise if you want.

In the near future, the starter will support the GraphQL multipart request spec out of the box.

**Comment by kaqqao** [comment]
Btw it is generally a best practice to handle dealing with binaries outside of GraphQL completely, so I highly recommend that is possible. The reason is that requiring optional specs breaks out-of-the-box compatibility with most clients.

**Comment by CengSin** [comment]
Thanks，I will try this and other methods.

**Comment by kaqqao** [comment]
I open an issue for multipart spec support https://github.com/leangen/graphql-spqr-spring-boot-starter/issues/44

**Comment by JonathanIlk** [comment]
I solved this by extending the GraphQLController of spqr like this:

```
@RestController
@CrossOrigin
public class CustomGraphQLController extends GraphQLController<NativeWebRequest> {

    @Autowired
    public CustomGraphQLController(GraphQL graphQL, TakkleGraphQLExecutor executor) {
        super(graphQL, executor);
    }

    /**
     * For Requests that follow the GraphQL Multipart Request Spec from: https://github.com/jaydenseric/graphql-multipart-request-spec
     *
     * The Request contains the following parts:
     * operations: JSON String with the GQL Query
     * map: Maps the multipart files to the variables of the GQL Query
     */
    @PostMapping(
            value = "${graphql.spqr.http.endpoint:/graphql}",
            consumes = {MediaType.MULTIPART_FORM_DATA_VALUE},
            produces = MediaType.APPLICATION_JSON_UTF8_VALUE
    )
    @ResponseBody
    public Object executeMultipartPost(@RequestPart("operations") String operations,
                                       @RequestPart("map") String map,
                                       MultipartHttpServletRequest multiPartRequest,
                                       NativeWebRequest webRequest) throws IOException, ServletException {
        GraphQLRequest graphQLRequest = new ObjectMapper().readerFor(GraphQLRequest.class).readValue(operations);
        Map<String, ArrayList<String>> fileMap = new ObjectMapper().readerFor(Map.class).readValue(map);

        mapRequestFilesToVariables(multiPartRequest, graphQLRequest, fileMap);
        return this.executeJsonPost(graphQLRequest, new GraphQLRequest(null, null, null), webRequest);
    }

    /**
     * Maps the files that were sent in a Multipart Request to the corresponding variables of a {@link GraphQLRequest}.
     * This makes it possible to use a file input like a normal parameter in a GraphQLApi Method.
     */
    private void mapRequestFilesToVariables(MultipartHttpServletRequest multiPartRequest, GraphQLRequest graphQLRequest,
                                            Map<String, ArrayList<String>> fileMap) throws IOException, ServletException {
        for (var pair : fileMap.entrySet()) {
            String targetVariable = pair.getValue().get(0).replace("variables.", "");
            if(graphQLRequest.getVariables().containsKey(targetVariable)) {
                Part correspondingFile = multiPartRequest.getPart(pair.getKey());
                graphQLRequest.getVariables().put(targetVariable, correspondingFile);
            }
        }
    }
}
```

This then enables me to use "Part" like a normal Scalar input, the corresponding Scalar is taken from ApolloScalars.Upload in the graphql-java-servlet.

    @Transactional
    @GraphQLQuery
    @NotNull
    public T_Entity uploadImage(@GraphQLContext T_MutationsObject mutationsObject, Part imageFile) throws IOException {

    }

**Comment by Rayoungji** [comment]
I wrote the same code above, but the following error is displayed.
->  "Validation error of type UnknownType: Unknown type upload"
Also  
I set up the upload scalar as follows

    @Bean
    @GraphQLQuery(name = "upload")
    GraphQLScalarType upload() {
        return ApolloScalars.Upload;
    }
