### ISSUE TITLE
GraphQLInterface scanPackages is not work

### ISSUE THREAD

**Issue by xf564246963** [leangen/graphql-spqr-spring-boot-starter#47]
scanPackages is not work
set package , but throw error "not implement interface...", these bean is not in same directory

**Comment by kaqqao** [comment]
You gave literally no information. How do you expect anyone to help you?
Give an example that demonstrates the issue. Without that, all I can tell you is: _yes, it works_.

**Comment by xf564246963** [comment]
@GraphQLInterface(name = "BaseDTO", implementationAutoDiscovery=true, scanPackages = {"com.packagename"})
public class BaseDTO {
    @JsonProperty(value = "create_time")
    private Long createTime;


    @JsonProperty(value = "update_time")
    private Long updateTime;

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}

===================================
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphQLSchema' defined in class path resource [io/leangen/graphql/spqr/spring/autoconfigure/SpqrAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'graphQLSchema' threw exception; nested exception is graphql.schema.validation.InvalidSchemaException: invalid schema:
object type 'GoalDetailInfo' does not implement interface 'BaseDTO' because field 'createTime' is missing
object type 'GoalDetailInfo' does not implement interface 'BaseDTO' because field 'updateTime' is missing

**Comment by xf564246963** [comment]
I find a way to fix this problem just as the other issues said, set base-packages in application.yml. Thx for your attention and it will be perfect if you can release a better documentation.
