### ISSUE TITLE
get Authentication with WebFlux

### ISSUE THREAD

**Issue by jonashao** [leangen/graphql-spqr-spring-boot-starter#50]
I have a need that get authentication inside `@GraphQLMutation` method, this might be a common need, as was mentioned in #11,  However when using with WebFlux, the solution mentioned there is out of style.

`SecurityContextHolder.getContext().getAuthentication()` will return `null` in WebFlux, as explained in this [StackOverflow post](https://stackoverflow.com/a/51350355/4206797)

>Because there is no way to use ThreadLocal objects anymore. The only way to get Authentication for you, is to ask for it in controller's method signature, or...
Return a reactive-chain from method, that is making a `ReactiveSecurityContextHolder.getContext()` call.

 In the case of this project, however, I cannot modify the Controller method, or return the reactive-chain that is making `ReactiveSecurityContextHolder.getContext()` call.

I found a workaround to return the reactive-chain,  by providing a custom `GraphQLReactiveExecutor`, like this:

```java
@Component
public class DefaultGraphQLExecutor implements GraphQLReactiveExecutor {

    @Autowired(required = false)
    @SuppressWarnings("SpringJavaAutowiredFieldsWarningInspection")
    private DataLoaderRegistryFactory dataLoaderRegistryFactory;


    @Override
    public Mono<Map<String, Object>> execute(GraphQL graphQL, GraphQLRequest graphQLRequest, ServerWebExchange request) {
        return ReactiveSecurityContextHolder.getContext()
                .flatMap(securityContext -> Mono.fromFuture(
                        graphQL.executeAsync(
                                buildInput(
                                        graphQLRequest,
                                        request,
                                        (params -> {
                                            DefaultGlobalContext<ServerWebExchange> context = new DefaultGlobalContext<>(params.getNativeRequest());
                                            context.setExtension("authentication", securityContext);
                                            return context;
                                        }),
                                        dataLoaderRegistryFactory)
                        ).thenApply(ExecutionResult::toSpecification)));
    }
}
```
Then I will be able to get authentication information inside `@GraphQLMutation` method by injecting:`@GraphQLRootContext DefaultGlobalContext<SecurityContextServerWebExchange> context` and calling ` context.getExtension("authentication").getAuthentication()`, 
```java
    @Transactional
    @GraphQLMutation
    public Authentication getAuthentication(
            @GraphQLRootContext DefaultGlobalContext<SecurityContextServerWebExchange> context) {
        SecurityContext securityContext = context.getExtension("authentication");
        return securityContext.getAuthentication();
    }
```

Is there any better way to achieve that?

**Comment by kaqqao** [comment]
I've just made a change that enables Spring Security to work normally with WebFlux and this starter. It does a similar thing you did here to capture the subscriber context in the executor and then piggy-backs on the GraphQL context to propagate it downstream.
This also means you can get to the `SecurityContext` anywhere in the usual WebFlux way: `ReactiveSecurityContextHolder.getContext()`.
See https://github.com/leangen/graphql-spqr-spring-boot-starter/issues/69 for details and caveats.

If you for whatever reason still want to get to the unwrapped `Authentication`, or modify the behavior in any other way, providing a custom executor and enhancing the GraphQL context is exactly the way to go (this is why those extension points are there in the first place).

I'll close this one now as it seems addressed, feel free to reopen if needed.
