### ISSUE TITLE
Firefox does not work with Subscriptions

### ISSUE THREAD

**Issue by kicktipp** [leangen/graphql-spqr-spring-boot-starter#54]
Firefox sends "Connection: keep-alive, Upgrade" instead of "Connection: Upgrade" hence the headers Mapping in GraphQLController does not work with Firefox (at least version 69.0.1).

See PR #53 
See https://github.com/leangen/graphql-spqr/issues/140

**Comment by kicktipp** [comment]
Is this going to be fixed soon? Is this project alive? I sent you a PR, so it should be easy to just pull and release a new version.

**Comment by BaldyLocks** [comment]
Project is alive but @kaqqao is handling some personal issues at the moment. This is all voluntary work for free on his part so he doesn't have a predictable or particularly quick release cycle as other things get in the way.

**Comment by kaqqao** [comment]
The related PR was merged long ago, so I guess this is safe to close?
