### ISSUE TITLE
Could we have a new release with spqr 0.10.0 ?

### ISSUE THREAD

**Issue by Loudsi** [leangen/graphql-spqr-spring-boot-starter#59]
Thank you for this starter. Could we have a new release with latest changes including spqr 0.10.0 ?

**Comment by Ernio3** [comment]
Duplicate #42 
Also looking forward to this.

**Comment by jm-ds** [comment]
Tried upgrading to 0.10.1 but still getting backwards comparability issues with 0.0.4 boot release. Any idea when you'll have some time to release 0.0.5?

Thanks. LOVE this project. Thank you for taking the time to build it!

**Comment by meddox** [comment]
What is missing to do release of 0.0.5 version? It seems to be ok.

**Comment by kaqqao** [comment]
There's been a release a while back and another one coming out today.
