### ISSUE TITLE
Annotations in different module

### ISSUE THREAD

**Issue by heruan** [leangen/graphql-spqr-spring-boot-starter#6]
It would be nice to have annotations in a different module, so to have a lightweight dependency in service modules and the Spring Boot autoconfiguration in the WAR only.

(Same as https://github.com/leangen/graphql-spqr/issues/170 for SPQR core.)

**Comment by BaldyLocks** [comment]
Agreed, would be a nicer solution. Likely will do it at some point before going stable.

**Comment by heruan** [comment]
This would be very useful, even before a stable release. Would you accept a PR for this?

**Comment by kaqqao** [comment]
Merged @heruan 's PR manually and will release it as a part of v0.0.4.
