### ISSUE TITLE
Pagination not working when graphql.spqr.base-packages property is defined

### ISSUE THREAD

**Issue by murtuza-ranapur** [leangen/graphql-spqr-spring-boot-starter#67]
Current starter version: **0.0.4**

I am trying to exposes properties of the parent class using graphql.spqr.base-packages property. But when i do it then the Queries that were returning Page object and were working perfectly fine started to fail. In schema explorer i am able to view only following properties:

1. totalElement
2. totalPage

**Comment by murtuza-ranapur** [comment]
I think i found the issue, as Page is part of _org.springframework.data.domain_ package when i enabled scanning on the selected package only it ignored the spring packages and hence the issue. Solution was to simply add org.springframework.data.domain in the property scanning.

**Comment by nxdefiant** [comment]
Awesome, you saved me some time. Thank you.
