### ISSUE TITLE
@GraphQLSubscription is not working

### ISSUE THREAD

**Issue by manaskumarsahoo** [leangen/graphql-spqr-spring-boot-starter#73]
I had done the setup for subscription as below,
`@GraphQLSubscription(name = "getSubscribedNotifications", description = "Get all Active notification")
	public Flowable<NotificationEntity> getSubscribedNotifications(
			@GraphQLArgument(name = "status", description = "Provide notification Status") @GraphQLNonNull Boolean status) {
		return this.notificationPublisher.getPublisher();
	} `

The query as below

`subscription{
  getSubscribedNotifications(status: true){
    active
  }
}
`

Response Always Getting as below
`{
  "error": "Could not connect to websocket endpoint ws://localhost:8083/graphql. Please check if the endpoint url is correct."
}`

**Comment by kaqqao** [comment]
Subscriptions don't yet work in reactive (WebFlux) apps. Is this your case, you didn't mention anything?

For MVC apps, a WebSocket endpoint will be registered at the address configured under `graphql.spqr.ws.endpoint` (in `application.properties`). If that's missing the same endpoint as for HTTP (`graphql.spqr.http.endpoint` will be used. Check all configs and default values in the [README](https://github.com/leangen/graphql-spqr-spring-boot-starter/blob/master/README.md#advanced-config).

Beyond this, you'll have to debug on your own. Subscriptions as such definitely do work (in MVC apps), so it's something with your setup.

**Comment by kaqqao** [comment]
Dependency to `spring-boot-starter-websocket` must be manually added, and `graphql.spqr.ws.enabled` should be set to `true` (the default).
Starter version v0.0.6 (currently in SNAPSHOT) also supports [subscriptions over SSE](https://github.com/leangen/graphql-spqr-spring-boot-starter/issues/97).
