### ISSUE TITLE
Support for configuring GraphQL object

### ISSUE THREAD

**Issue by sophiewithaph** [leangen/graphql-spqr-spring-boot-starter#8]
Currently the DefaultGraphQLController autowires a GraphQLSchema, and builds a default GraphQL object. This doesn't leave room to configure an ExecutionStrategy or Instrumentation. The DefaultGraphQLController could instead autowire a GraphQL, which can be overridden for custom configuration.

**Comment by BaldyLocks** [comment]
Agreed. That would add some flexibility. Will include such capability for 0.0.3

**Comment by EdgarArguelles** [comment]
Hi @BaldyLocks or @sophiewithaph is there any example when GraphQL is overridden for custom configuration???

I would like to include Instrumentation to the GraphQL used by graphql-spqr-spring-boot-starter
