### ISSUE TITLE
Potential Incompatibility with WebJars Locator

### ISSUE THREAD

**Issue by heathharrelson** [leangen/graphql-spqr-spring-boot-starter#86]
Upgrading to Spring Boot 2.3 can cause issues if your project depends on both graphql-spqr-spring-boot-starter 0.0.4 and webjars-locator 0.40. Note that I'm largely submitting this issue to help others who may have the same error. This isn't strictly a bug in the project.

On startup, my project threw the following error:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.webjars.WebJarAssetLocator.findWebJars(WebJarAssetLocator.java:112)

The following method did not exist:

    'java.net.URI io.github.classgraph.Resource.getClasspathElementURI()'

The method's class, io.github.classgraph.Resource, is available from the following locations:

    jar:file:/app.jar!/BOOT-INF/lib/classgraph-4.6.7.jar!/io/github/classgraph/Resource.class

It was loaded from the following location:

    jar:file:/app.jar!/BOOT-INF/lib/classgraph-4.6.7.jar!/


Action:

Correct the classpath of your application so that it contains a single, compatible version of io.github.classgraph.Resource
```

Both GraphQL SPQR and webjars-locator-core depend on ClassGraph, but due to Maven's dependency resolution algorithm, the older version of the dependency from GraphQL SPQR 0.9.9 wins in my project, causing the startup error.

I resolved this by overriding the version of ClassGraph used, which seems to work.

```diff
+               <!-- override ClassGraph to prevent conflict between WebJars and GraphQL SPQR -->
+               <dependency>
+                       <groupId>io.github.classgraph</groupId>
+                       <artifactId>classgraph</artifactId>
+                       <version>4.8.87</version>
+               </dependency>

                <dependency>
                        <groupId>io.leangen.graphql</groupId>
                        <artifactId>graphql-spqr-spring-boot-starter</artifactId>
                        <version>${spqr.starter.version}</version>
                </dependency>
```

This could also be resolved by releasing a version of graphql-spqr-spring-boot-starter that uses GraphQL SPQR 0.10, which depends on a compatible version of ClassGraph.

**Comment by kaqqao** [comment]
[Release v0.0.5](https://github.com/leangen/graphql-spqr-spring-boot-starter/releases/tag/graphql-spqr-spring-boot-starter-v0.0.5) has the latest ClassGraph version. In addition, I'm looking into _possibly_ replacing ClassGraph with Jandex (for unrelated reasons).

**Comment by heathharrelson** [comment]
Thanks for the updated release! This project significantly reduces the effort needed to create a GraphQL API in Java, so I'm excited to see renewed development on it.
