### ISSUE TITLE
Lombok + SPQR

### ISSUE THREAD

**Issue by nautilor** [leangen/graphql-spqr-spring-boot-starter#87]
Hello,

I am trying to achieve something like this

     @Builder
     @NoArgsConstructor
     @AllArgsConstructor
     @EqualsAndHashCode
     @Data
     public class User {

         private String username;

         private String firstName;

         private String lastName;

         @GraphQLQuery(name = "emailAddress", description = "The user email")
         private String email;

     }

I know spqr cannot access private fields and I would have to generate getters to acheive this but I was wondering if there was a way to do this and still benefit of lombok `@Data`

I have found

     @Getter(onMethod = @__(@GraphQLQuery(name = "emailAddress", description = "The user email")))
     private String email;

this does work still not quite clean In my opinion

**Comment by dupengcheng** [comment]
@nautilor 
 add 
@Setter
@Getter

like this :
```java
@Data
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Person {

    @Id
    @GeneratedValue
    @Type(type = "uuid-char")
    private UUID id;

    private String name;

    @GraphQLQuery(name = "years", description = "The person age")
    private Integer age;

}
```

![image](https://user-images.githubusercontent.com/11847818/88127596-a054bf00-cc06-11ea-834e-5a4702713a10.png)
