### ISSUE TITLE
Authentication and Authorization Support

### ISSUE THREAD

**Issue by arslanakhtar61** [leangen/graphql-spqr-spring-boot-starter#89]
Are there any plans to formally include authentication and authorization support that can integrate with spring boot security?

An example use case is to allow certain public methods like `login` that is accessible by an unauthenticated user and other private methods by only authenticated users with appropriate authorization.

 So far I have been looking into [Spring-AOP
 ](https://medium.com/trabe/graphql-authorization-with-spqr-and-custom-annotations-2b22659ca5b0) to implement this but I wonder wouldn't it be nice if `graphql-spqr-spring-boot-starter` could support this.

**Comment by vetemi** [comment]
You can use Spring Security just as you would use it without graphql-spqr. Example:

```
  @GraphQLQuery(name = "example)
  @PreAuthorize("isAuthenticated()")
  public Object example() {
    // do something here ...
  }
```

Actually, you can use Spring Security Annotation anywhere in your project, so it has nothing to do with GraphQL spqr. Have a look in the [Spring Docs](https://docs.spring.io/spring-security/site/docs/current/reference/html5/) for more information.

**Comment by kaqqao** [comment]
Why reinvent security on Spring? Spring Security is insanely configurable, easy to use, fantastically documented and integrates perfectly with other Spring features.
As @vetemi said, you can use `@PreAuthorize` or other Spring Security features normally with SPQR. Note that there was [a bug](https://github.com/leangen/graphql-spqr-spring-boot-starter/issues/100) in versions prior to v0.0.6 that interferes when JDK proxies are used (CGLIB proxies did not cause issues).

If you end up going for a custom implementation, you can use a [`ResolverInterceptor`](https://github.com/leangen/graphql-spqr/blob/graphql-spqr-v0.11.2/src/test/java/io/leangen/graphql/InterceptorTest.java#L96) as exemplified in [this test](https://github.com/leangen/graphql-spqr/blob/graphql-spqr-v0.11.2/src/test/java/io/leangen/graphql/InterceptorTest.java#L34).
