### ISSUE TITLE
Release 0.0.5

### ISSUE THREAD

**Issue by MarcinLachowicz** [leangen/graphql-spqr-spring-boot-starter#91]
Hello,

could you please release 0.0.5 version?

**Comment by alexandrenavarro** [comment]
up

**Comment by Maclaon** [comment]
> up

can not find 0.0.5 version in [graphql-spqr-spring-boot-starter](https://mvnrepository.com/artifact/io.leangen.graphql/graphql-spqr-spring-boot-starter)!

**Comment by kaqqao** [comment]
0.0.5 has been released a while back: https://github.com/leangen/graphql-spqr-spring-boot-starter/releases/tag/graphql-spqr-spring-boot-starter-v0.0.5

0.0.6 is in the works.

**Comment by MarcinLachowicz** [comment]
Thank you!
