### ISSUE TITLE
The same object type can not be an input and an output at the same time

### ISSUE THREAD

**Issue by osaiko** [leangen/graphql-spqr-spring-boot-starter#94]
The situation is this. The same object type can not be an input and an output at the same time in GraphQL. So when you use InventoryInfo class as both the input and as output, SPQR generates 2 different types: InventoryInfo and InventoryInfoInput
I think the mapper could not find any fields on it.
The way this works in SPQR is that it asks the JSON library you use (Jackson by default) what fields are deserializable, and maps only those fields. This is because if Jackson won’t be able to deserialize the input, there’s no point in mapping it.
Anyway, I think that jackson finds 0 deserializable fields in your case and types with 0 fields are not allowed.

**Comment by kaqqao** [comment]
Was this a response to some other issue? Why open a new issue?
